spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_mybatis?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: mysql0205
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
mybatis:
  mapper-locations: classpath:/mapping/*.xml
  type-aliases-package: com.lei.po