spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_mybatis?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: mysql0205
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true #sql语句输出
    properties:
      hibernate:
        format_sql: true  #sql语句进行格式化
